name: Deploy to Firebase and Push to DockerHub

on:
  push:
    branches:
      - main

jobs:
  # -----------------------------------------------
  # JOB 1: Build & Push to DockerHub
  # This job builds the Dockerfile and pushes it to
  # DockerHub.
  # -----------------------------------------------
  build-and-push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # This name must be unique for this project
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-firebase:latest

  # -----------------------------------------------
  # JOB 2: Deploy to Firebase Hosting
  # This job takes the static files (index.html, etc.)
  # and deploys them to Firebase Hosting.
  # -----------------------------------------------
  deploy-to-firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This is the official Firebase action
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # This is the secret token you will generate
          token: ${{ secrets.FIREBASE_TOKEN }}

          # This is the Firebase Project ID
          projectId: "hello-world-firebase-640c3"
